/// Flutter icons Windows
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Windows
///      fonts:
///       - asset: fonts/Windows.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Windows {
  Windows._();

  static const _kFontFam = 'Windows';
  static const _kFontPkg = null;

  static const IconData uniE001 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE10A = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE108 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE115 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE094 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE0A6 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE0AB = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE15D = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE701 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE702 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE704 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE706 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE705 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE708 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE709 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE70B = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE72D = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE777 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE7E8 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE7E7 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE7F7 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE12B = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE125 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE1DC = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE1E2 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE010 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE011 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE00E = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE00F = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE10C = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE14C = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE17D = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE117 = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE8B2 = IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE8B7 = IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE922 = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE923 = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE943 = IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE947 = IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE948 = IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE949 = IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE94A = IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE94B = IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniE94C = IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniEBA5 = IconData(0xeba5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniEBB4 = IconData(0xebb4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniEBB5 = IconData(0xebb5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniEC3F = IconData(0xec3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniEC42 = IconData(0xec42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniEC54 = IconData(0xec54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniED0C = IconData(0xed0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniEE56 = IconData(0xee56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniEE77 = IconData(0xee77, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniEE7A = IconData(0xee7a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
